import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import React from 'react'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'AI Website Builder',
    description: 'Generated by create next app',
}

import { ThemeProvider } from './context/ThemeContext'
import { NotificationProvider } from './context/NotificationContext'

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" className="h-full">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased h-full dark:bg-slate-950 text-slate-900 dark:text-slate-200`}
        >
        <ThemeProvider>
            <NotificationProvider>
                <div className="fixed inset-0 -z-10 bg-space">
                    <div className="absolute inset-0"></div>
                    <div className="absolute inset-0 dark:bg-gradient-to-br dark:from-slate-900/90 dark:via-slate-900/70 dark:to-slate-900/90"></div>
                    <div className="absolute inset-0 bg-grid bg-[length:22px_22px]"></div>
                    <div
                        className="absolute -top-24 -left-24 h-96 w-96 rounded-full blur-3xl opacity-20"
                        style={{
                            background:
                                'radial-gradient(circle at center, #40ccff55, #00000000 60%)',
                        }}
                    ></div>
                    <div
                        className="absolute -bottom-32 -right-24 h-[28rem] w-[28rem] rounded-full blur-3xl opacity-20"
                        style={{
                            background:
                                'radial-gradient(circle at center, #7c3aed55, #00000000 60%)',
                        }}
                    ></div>
                </div>
                {children}
            </NotificationProvider>
        </ThemeProvider>
        </body>
        </html>
    )
}
